// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWtTIlHFvdGeAxbZ7GXqnjJQYHIGI7Rq0',
    appId: '1:837256889960:web:8fb078bd2860ae75ba9ddd',
    messagingSenderId: '837256889960',
    projectId: 'social-midia-f66b1',
    authDomain: 'social-midia-f66b1.firebaseapp.com',
    storageBucket: 'social-midia-f66b1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD04SRQEoFa4iUzblDODG9tdVICDsdQ7T0',
    appId: '1:837256889960:android:5f2fe329a3d8268eba9ddd',
    messagingSenderId: '837256889960',
    projectId: 'social-midia-f66b1',
    storageBucket: 'social-midia-f66b1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsCDZsRC6CGlOzhJxyG-1jYodsOss0kSs',
    appId: '1:837256889960:ios:259d14e53dabd309ba9ddd',
    messagingSenderId: '837256889960',
    projectId: 'social-midia-f66b1',
    storageBucket: 'social-midia-f66b1.appspot.com',
    iosBundleId: 'com.example.socialMidiaFirebase',
  );
}
